chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^chat/', include('msgs.urls', namespace='msgs')),
]

msgs/urls.py
from django.conf.urls import url
from msgs.views import chat

urlpatterns = [
    url(r'^(?P<user>[\w.@+-]+)/$', chat, name='chat'),
]

users/urls.py
from django.conf.urls import url
from users.views import log_in, log_out, user_list


urlpatterns = [
    url(r'^login/$', log_in, name='log_in'),
    url(r'^logout/$', log_out, name='log_out'),
    url(r'^$', user_list, name='user_list')
]

msgs/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
from django.utils import timezone


class Message(models.Model):
    text = models.TextField()
    room = models.ForeignKey('msgs.Room', on_delete=models.CASCADE)
    from_user = models.OneToOneField(User)
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)


class Room(models.Model):
    name = models.CharField(max_length=265, blank=True)
    from_user = models.ForeignKey(User, related_name='from_user', null=True)
    to_user = models.ForeignKey(User, related_name='to_user', null=True)

    def __str__(self):
        return "%s-%s".format(self.from_user.first_name, self.to_user.first_name)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(Room, self).save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        self.name = self.__str__()

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class LoggedIn(models.Model):
    user = models.OneToOneField(User)

msgs/forms.py
from msgs.models import Message
from django import forms


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

msgs/views.py
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from msgs.forms import MessageForm
from msgs.models import Room

User = get_user_model()

@login_required(login_url='/login/')
def chat(request, user):
    user = User.objects.get(username=user)
    try:
        room = Room.objects.get(from_user=request.user, to_user=user)
    except Room.DoesNotExist:
        room, created = Room.objects.get_or_create(to_user=request.user, from_user=user)

    messages = reversed(room.message_set.order_by('-timestamp')[:50])

    return render(request, "msgs/chat.html", {
        'room': room,
        'messages': messages,
        'form': MessageForm
    })

users/views.py
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView

from users.models import LoggedIn

User = get_user_model()

@login_required(login_url='/login/')
def user_list(request):
    try :
        LoggedIn.objects.create(user=request.user)
    except IntegrityError:
        pass
    users = User.objects.select_related('loggedin')
    for user in users:
        user.status = 'Online' if hasattr(user, 'loggedin') else 'Offline'

    return render(request, 'registration/list.html', {'users': users})


log_in = LoginView.as_view()


class MsgLogoutView(LogoutView):
    next_page = 'msgs:log_in'

    def dispatch(self, request, *args, **kwargs):
        user = getattr(request, 'user', None)
        try:
            loggedin_user = LoggedIn.objects.get(user=user)
            loggedin_user.delete()
        except LoggedIn.DoesNotExist:
            pass
        logout(request)
        next_page = self.get_next_page()
        if next_page:
            # Redirect to this page until the session has been cleared.
            return HttpResponseRedirect(next_page)
        return super(LogoutView, self).dispatch(request, *args, **kwargs)
log_out = MsgLogoutView.as_view()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <title>Example Chat Channels</title>

</head>
<body>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html>

templates/msgs/chat.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'users:log_out' %}">Log out</a>
    <br>
    <ul>
        {% for msg in msgs %}
            <li>{{ msg.text }}</li>
        {% endfor %}
    </ul>

    {% endif %}
    <form method="post" action="." id="chatform">
    {% csrf_token %}
    {{ form.as_p }}
    <input value="Send" type="submit">
    </form>
{% endblock content %}

{% block script %}
  <script>
    var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
    var socket = new WebSocket(ws_scheme + '://' + window.location.host + window.location.pathname);
    console.log(socket.url);
    socket.onopen = function open() {
      console.log('WebSockets chat connection created.');
    };
    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
        console.log(data);
       var chat = $("#chat")
        var ele = $('<tr></tr>')

        ele.append(
            $("<td></td>").text(data.timestamp)
        );
        ele.append(
            $("<td></td>").text(data.handle)
        );
        ele.append(
            $("<td></td>").text(data.message)
        );

        chat.append(ele)
    };
    $("#chatform").on("submit", function(event) {
        var message = {
            message: $('#id_text').val(),
        };
        socket.send(JSON.stringify(message));
        $("#id_text").val('').focus();
        return false;
    });

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
    socket.onclose = function close(){
        console.log('connection go out');
    }
  </script>
{% endblock script %}

templates/msgs/list.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'msgs:log_out' %}">Log out</a>
    <br>
    <ul>
    {% for user in users %}
      <!-- NOTE: We escape HTML to prevent XSS attacks. -->
      <li data-username="{{ user.username|escape }}">
        {{ user.username|escape }}: {{ user.status|default:'Offline' }}
      </li>
    {% endfor %}
    </ul>
    {% else %}
    <a href="{% url 'msgs:log_in' %}">Log out</a>
    {% endif %}
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('ws://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };
    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      var username = encodeURI(data['username']);
      var user = $('li').filter(function () {
        return $(this).data('username') == username;
      });
      console.log(user);
      console.log(data);

      if (data['is_logged_in']) {
        user.html(username + ': Online');
      }
      else {
        user.html(username + ': Offline');
      }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
    socket.onclose = function close(){
        console.log('connection go out');
    }
  </script>
{% endblock script %}